### ISSUE TITLE
README file unvollstaendig

### ISSUE THREAD

**Issue by Vince3453463** [smtinova/wissArbeiten_gruppenarbeit#1]
Es fehlt in dem readme file noch die  Nennung der Autoren und Autorinnen und eine kurze Zusammenfassung der Aufgabenstellung.

**Comment by novaktim** [comment]
Okay, wird noch gemacht. Wie würdest du die Aufgabenstellung zusammenfassen? Statistik über Studierende der Fakultäten Mathematik, Statistik und Informatik? Ich sehe noch nicht ganz, wo die Reise bisher hingeht. Oder die tatsächliche Aufgabenstellung reinschreiben? Aber dürfen wir das aus Copyright-Sicht?

**Comment by Vince3453463** [comment]
Hallo, vielleicht einfach die Aufgabenstellung kopieren? Dann ist die auch hier verewigt, ich sehe darin keine Copyright Verletzung. Ich denke, wir können das readme auch kontinuierlich updaten, wenn wir neuen Code o.ä. geschrieben haben, den Fortschritt im readme festhalten. Dann können alle Gruppenmitglieder sofort nachvollziehen, was bereits getan wurde und was als nächstes zu tun ist.

**Comment by novaktim** [comment]
Die Aufgabenstellung wurde hinzugefügt. Allerdings gibt es nun einen Pull-Konflikt mit @CynthiaN01 . Das werde ich ASAP lösen.
