### ISSUE TITLE
Conflicts in Pull Requests

### ISSUE THREAD

**Issue by Hanjin99** [smtinova/wissArbeiten_gruppenarbeit#18]
Mir ist es aufgefallen, dass es bei einigen Pull requests **conflict** gibt. 

Situation: Ihr habt ein branch erstellt und darauf eure Funktionen hinzugefügt. Nun möchtet ihr euer branch in main mergen, aber da steht, dass euer branch einen Konflikt mit main hat.

Problem: Euer branch ist nicht aktuell mit main, da jemand seine Funktionen in main gemergt hat, aber ihr euer branch nicht aktualisiert habt. Das heißt ihr habt eure Funktionen auf das alte main hinzugefügt.

Lösung: Speichert eure Funktionen erstmal lokal ab. Danach solltet ihr euer branch mit main aktualisieren. 

Falls ihr online auf github.com macht, dann müsstet ihr einen Pull request erstellen und in base wählt ihr euer branch aus und in compare wählt ihr main aus. Danach einfach mergen.
Falls ihr GitHub Desktop benutzt, einfach in euer branch gehen und STRG + SHIFT + U drücken. GitHub Desktop updatet euer branch automatisch, ihr müsstet danach nur noch einmal pushen.

Nach dem Aktualisieren fügt ihr eure Funktionen wieder hinzu und nun könntet ihr einen neuen Pull request ohne Konflikt erstellen.

Das wäre meine Lösung, vielleicht hat jemand einen besseren Weg, gerne hier posten :)

**Comment by Hanjin99** [comment]
Für Mac OSX: 
https://stackoverflow.com/questions/59916041/how-to-update-a-branch-with-master-on-github

**Comment by CynthiaN01** [comment]
Danke, ich probiere das mal aus.

**Comment by Hanjin99** [comment]
Falls es bei STRG + SHIFT + U immer noch **conflict** gibt, dann kann man ein neues branch erstellen und damit pull requests erstellen. Vergesst nicht das alte branch zu löschen :)
