### ISSUE TITLE
Aufgabe 4

### ISSUE THREAD

**Issue by Vince3453463** [smtinova/wissArbeiten_gruppenarbeit#20]
@Jan-Enno-Jonas  @Hanjin99 

Ich schlage vor, wie diskutieren hier über Aufgabe 4. Ich denke, wir können unseren Code direkt im Main schreiben in das file von Hanjin, da wir ja nichts komplexes programmieren müssen, sondern nur die Funktionen auf den Datensatz aufrufen müssen. Wichtig ist es, jede Funktion muss mind. einmal benutzt werden. Noch sind nicht alle Funktionen im Main, aber ich denke, wir können schonmal etwas anfangen. 

Ich habe 2 Funktionen einige Male aufgerufen und darunter auskommentiert, wie ich das Ergebnis interpretiere. Ich schlage vor, wir machen das so ähnlich für die anderen Funktionen auch. Nehmt euch einfach eine Funktion heraus und wendet sie auf sinvolle Teile des Datensatzes an.

**Comment by Jan-Enno-Jonas** [comment]
Ok gute Idee ich habe es gerade für 3 f) gemacht...

**Comment by Jan-Enno-Jonas** [comment]
Ich mache auch d

**Comment by Jan-Enno-Jonas** [comment]
sorry meinte b d hat ja schon Vincent gemacht

**Comment by Jan-Enno-Jonas** [comment]
Toll ich meinte c 

Komme jetzt mit den Buchstaben ganz durcheinander Sorry...

**Comment by Hanjin99** [comment]
`kategorialeVariablen(df$Studienfach, Merkmal = qualitativ)`
`# funktioniert nicht?`

@Vince3453463 Bei _qualitativ_ fehlt ""
kategorialeVariablen(df$Studienfach, Merkmal = "qualitativ")
Nun funktioniert es.

**Comment by Hanjin99** [comment]
@Vince3453463 
Ich werde weiterhin in meinem branch schreiben und pull requests erstellen, denn wenn wir drei gleichzeitig in main commiten, könnte es wieder Konflikten geben.

**Comment by Hanjin99** [comment]
@Jan-Enno-Jonas 
Hast du vielleicht eigene _Visualisierung()_ Funktion geschrieben?
Bei mir habe ich die Fehlermeldung:
`Error in Visualisierung(df) : could not find function "Visualisierung"`

**Comment by Jan-Enno-Jonas** [comment]
Ja ist noch nicht im Main

**Comment by Vince3453463** [comment]
Aufgabe abgeschlossen.
