### ISSUE TITLE
Aufgabe 5

### ISSUE THREAD

**Issue by Jan-Enno-Jonas** [smtinova/wissArbeiten_gruppenarbeit#28]
Zum Diskutieren:

**Comment by Jan-Enno-Jonas** [comment]
Die Studienfächer Statistik und Data Science sind im Datensatz am häufigsten belegt und Mathe und Informatik am wenigsten, dies könnte daran liegen, dass es einfach weniger Informatiker und Mathematiker gibt, als Statistik und Data Science Studierende, aber es kann auch daran liegen wie die Daten erhoben wurden sind, hier können Cynthia und Tim und uns mehr Aufschluss geben. Außerdem haben deutlich mehr als die Hälfte der Studierenden aus dem Datensatz an einem Mathe LK teilgenommen, hier ist ebenfalls wichtig zu wissen, wie hier die Erhebung des Datensatzes hierauf Einfluss genommen hat.
Beim Anschauen des Kontigenzmaß für Mathe LK und Interesse an Mathematik können wir einen mittleren Zusammenhang identifizieren, es ergibt sich ein Cramer-Kontigenzmaß von 0,274. 
Der Zusammenhang von Mathe LK und Interesse an Programmieren hat ebenfalls einen mittleren Zusammenhang von einem Cramer-Kontingenzmaß von 0,44.

**Comment by Vince3453463** [comment]
@Jan-Enno-Jonas bezüglich des Zusammenhangs zwischen Interesse und Mathe LK ist auch wichtig, dass wir einen positiven Zusammenhang von Interesse an Mathematik und Mathe LK festgestellt haben, aber einen negativen zwischen Interesse an Programmieren und Mathe LK.

Weitere, wichtige Erkenntnisse:
 Anhand der bedingten Verteilungen sieht man, dass Personen mit mittleren Interesse an Mathematik (3-4) den höchsten Anteil an den Personen, die keinen Mathe LK hatten, ausmachen. Anders ausgedrückt, Personen mit Mathe LK haben entweder ein sehr hohes oder ein sehr niedriges Interesse an Mathematik! Eine überraschende Entdeckung.
Außerdem haben Personen mit großem Interesse am Programmieren eine niedrige Wahrscheinlichkeit, den Mathe LK besucht zu haben.

Außerdem konnten wir einen starken Zusammenhang zwischen Studienfach und Interesse an Mathematik/ Programmieren finden: Data Scientisten und Informatiker haben ein eher geringes Interesse an Mathematik verglichen mit Statistikern  und Mathematikern und Data Scientisten haben ein hohes Interesse am Programmieren, Informatiker ein sehr hohes, Statistiker ein mittleres und Mathematiker ein eher niedriges Interesse. Dies entspricht unseren Erwartungen, wer gerne programmiert, wählt logischerweise ein Studienfach, wo Programmieren eine große Rolle spielt. Analog gilt das gleiche für die Mathematik.

Der Zusammenhang zwischen Interesse an Mathematik und Interesse am Programmieren ist dagegen stark negativ. Manche coden lieber, die Anderen rechnen lieber, aber nur sehr wenige mögen beides gleichzeitig.

**Comment by Hanjin99** [comment]
Ergänzung:

Das Durchschnittsalter bei den befragten Personen beträgt etwa 25 Jahre. Das durchschnittliche Interesse an Programmieren (4,6 von 7) ist höher als das durchschnittliche Interesse an Mathematik (3,9 von 7). Dazu muss man aber erwähnen, dass nur 11% von den befragten Personen Mathematik studieren. Etwa doppelt so viele Personen (23%) haben das Studienfach Informatik. Die meisten Personen studieren Statistik (36%) und Data Science (30%).

**Comment by Vince3453463** [comment]
Ich glaube, wir haben jetzt unsere wichtigsten Erkenntnisse zusammengefasst. Weitere, genaue Ergebnisse findet man in der enstprechenden R Datei, auskommentiert unter den Befehlen.

@smtinova  @CynthiaN01  Vielleicht könnt ihr ja jetzt erklären, wie ihr den Datensatz konstruiert habt und was ihr von unseren Ergebnissen hält.

**Comment by novaktim** [comment]
Die Wahrscheinlichkeiten der Studienfächer habt ihr ganz grob richtig erfasst. Nach Vorgabe tritt Statistik und Data Science mit der selben und gleichzeitig größten W'keit auf. Gefolgt von Informatik und zuletzt Mathematik mit der geringsten W'keit. Diese wurden für alle nach der Multinomialverteilung (mit sample) gezogen, daher kann es zu leichten Abweichungen kommen.
Die einzelnen W'keiten wurden unter anderem aus irrationalen Zahlen erstellt. Daher hättet ihr niemals die Wahrheit erreichen können, ich hoffe das deprimiert euch jetzt nicht.

Das Verfahren war hochkomplex. Im Prinzip bekamen Statistik/DS beide den vorläufigen Wert von 3,5 (E-Wert eines Würfelwurfs), Informatik pi und Mathe e (Eulersche Zahl). Dann wurde diese um 2 subtrahiert, um deren relative Abstände zueinander zu vergrößern und letztlich dann auf 100% normiert, indem alle durch die Summe geteilt werden.

Die wahren W'keiten aus den gezogen wurden waren also:
0.3086499 für Statistik / Data Science
0.2349017 für Informatik
0.1477984 für Mathematik

**Comment by novaktim** [comment]
Mit dem Alter hat @Hanjin99 recht, denn dieses wurden aus der N(25, 4) Normalverteilung gezogen. Also sollte der Durchschnitt auch bei 25 Jahren liegen.

**Comment by CynthiaN01** [comment]
Bei dem Interesse an Mathematik und an Programmieren lagt ihr auch mit fast allem richtig.

**Comment by CynthiaN01** [comment]
Beim Interesse an Mathematik und an Programmieren lagt ihr auch soweit richtig.
Wir haben das Interesse in Abhängigkeit vom Studienfach jeweils aus einer anderen Binomialverteilung gewählt.
Bei Mathematik haben wir 0,3 für Informatik, 0,4 für Data Science, 0.6 für Statistik und 0.85 für Mathe als W'keit und n = 6 genommen um aus 7 Möglichkeiten (0-6) Zufallszahlen zu ziehen.

**Comment by CynthiaN01** [comment]
Beim Interesse an Mathematik und an Programmieren lagt ihr auch soweit richtig.
Wir haben das Interesse in Abhängigkeit vom Studienfach jeweils aus einer anderen Binomialverteilung gewählt.
Bei Mathematik haben wir 0,3 für Informatik, 0,4 für Data Science, 0.6 für Statistik und 0.85 für Mathe als W'keit und n = 6 genommen um aus 7 Möglichkeiten (0-6) Zufallszahlen zu ziehen.
Beim Programmieren war es fast anders herum. Dort nahmen wir genauso willkürlich 0,25 0,42 0,7 & 0,9 bei Mathe, Statistik, Data Science und Informatik als W'keit für die Binomialverteilung.
Daher ist in die eine Richtung das Interesse an Mathematik und in die andere Richtung das an Programmieren höher. Dadurch entstand auch der starke negative Zusammenhang, den ihr erwähnt habt.
Die beiden Variablen hingen ansonsten von nichts anderem ab.

**Comment by novaktim** [comment]
Auch bei Mathe-LK sind wir unserem Binomial-Verfahren treu geblieben. Die Wahrscheinlichkeit Mathematik als Leistungskurs zu haben ist 0.67 + (Interesse_Mathe - Interesse_Informatik) / 6 * 0.3
Da die Interessen von 1 bis 7 gehen, kann die Differenz also größtens 6 betragen. Deshalb haben wir durch 6 geteilt. Folglich kann sich p nur zwischen 0.37 und 0.97 befinden. Wir dachten uns dabei, dass entscheidend sein soll wie viel jemand Mathematik mehr mag als Informatik. Ob jemand (3, 3)  oder (5, 5) bei Interessen ankreuzt hat deshalb die gleiche W'keit, da es z.B. Menschen gibt, die einfach grundsätzlich hohe oder niedrige Punkte auf einer Skala vergeben.

**Comment by CynthiaN01** [comment]
Wie ihr seht war es hier etwas komplizierter, deswegen konntet ihr auch mit unseren zweidimensionalen Analyseverfahren nicht direkt auf eindeutige Ergebnisse kommen.
Dadurch, dass Mathe.LK von beiden Interessen abhing, ist die Annahme eines mittleren Zusammenhangs zu jedem einzelnen Interesse nicht falsch.
Durch unsere Formel haben, wie ihr gesagt habt, Studierende mit hohem Interesse an Programmieren wahrscheinlich eher kein Mathe LK.
Studierende mit Mathe LK haben meistens ein höheres Interesse an Mathematik. Wenn Studierende ein niedriges Interesse an Mathematik haben und trotzdem dem Mathe LK belegten, dann liegt das hier nur daran, dass ihr Interesse an Programmieren noch geringer war.
Insgesamt konntet ihr aber die groben Zusammenhangsstrukturen, die Tim und ich uns ausgedacht haben erkennen.

**Comment by CynthiaN01** [comment]
Welche Funktionen haben euch am meisten bei der Analyse geholfen und welche fandet ihr nicht sinnvoll?

**Comment by Jan-Enno-Jonas** [comment]
Für den Zusammenhang fand ich die Funktion aus 3 c sehr hilfreich wohin gegen ich mit der Visualisierung keine Zusammenhänge erkennen konnte, aber dafür die Anzahl…

Die 3c fand ich aber sinnvoller, da ich dadurch ein tieferes Verständnis bekommen hab, als nur mit den Grafiken.

**Comment by Hanjin99** [comment]
> Welche Funktionen haben euch am meisten bei der Analyse geholfen und welche fandet ihr nicht sinnvoll?

Die Funktionen _e_ und _f_ waren dabei nicht so sinnvoll. Das Ergebnis aus _e_, kann ich nicht sinnvoll interpretieren und die Grafik aus _f_ liefert die Informationen, die wir schon bei _b_ erhalten haben.

Die Funktionen _a_ und _b_ sind sinnvoll, um allgemeine Information aus metrische und kategoriale Daten zu bekommen. (Durchschnitt, Median, Modalwert, absolute Häufigkeit, relative Häufigkeit, ...)

Am meisten haben die Funktionen _c_, _d_ und `rangkorr_koeff` uns bei der Analyse geholfen, um Zusammenhänge zwischen den Daten zu erkennen.

**Comment by Vince3453463** [comment]
Sehr interessante und kreative Weise, wie ihr den Datensatz erstellt habt!

Ich fand die relate_categorial Funbktion sehr hilfreich, da hat man sehr schnell viele Informationen bekommen. quantilKategorisierung dagegen fand ich nicht so hilfreich.

**Comment by CynthiaN01** [comment]
Ich denke auch, dass die Funktionen zur Analyse von Zusammenhängen sehr nützlich waren.
Mir haben auch die Grafiken aus A3 f) gefallen, denn manchmal erkennt man schneller die Verteilung von verschiedenen Variablen über einen plot, als nur über Werte. Trotzdem konnte man erst mit den Statistiken aus a) und b) feste Aussagen zu den Variablen machen.
Die Quantile haben mir auch keine bedeutenden neue Aufschlüsse gegeben, die man nicht schon vorher sah. Diese Funktion haben wir also eher nicht gebraucht.
Wir hätten vielleicht noch eine Funktion gebrauchen können, die den Zusammenhang von mehr als 2 Variablen analysiert.

**Comment by novaktim** [comment]
Ich denke wäre die Stichprobengröße noch höher z. B. N = 200 gewesen, hätten sich die Wahrscheinlichkeitsverteilungen mit (a), (b) noch besser herstellen lassen. Da es nur 100 Studenten waren, studierten aufgrund des Zufalls 36 Statistik und 30 Data Science, obwohl beide mit gleicher W'keit auftreten sollten.

Statt der Quantile-funktion aus (e) hätte vielleicht ein Histogramm besser funktioniert. Dann würde man ebenfalls die Daten in mehrere Klassen einteilen, aber zusätzlich ist die Art der Verteilung (Normalverteilung, Gleichverteilung, etc.) leichter zu bestimmen.
Oder falls die Daten nicht nur ein Maxima haben, sondern bimodal verteilt gewesen wären. Dann lassen sich die Extremstellen leichter ablesen.

Ich glaube auch, dass man eine Funktion für den Zusammenhang mehrerer metrischer Variablen gebraucht hätte. Vielleicht hätte ein multivariates Lineares Modell den richtigen Zshg. zwischen Mathe-LK und Interesse an Mathematik/Programmieren hergestellt.

**Comment by Vince3453463** [comment]
Zusammengefasst lässt sich sagen, dass das Erstellen von allgemeinen Funktionen zur Deskription und Visualisierung von Datensatz die Arbeit sehr erleichtert. Mit den Funktionen aus Aufgabe 3 konnten wir den Datensatz sehr effizient und präzise analysieren und interpretieren.
Außerdem ist Github eine sehr gute Platform zur Zusammenarbeit an Projekten wie diesen, insbesondere die Arbeit im eigenen Branch und anschließendem Zusammenführen der Aufgabenteile half uns sehr.
