### ISSUE TITLE
private Nachrichten für A1?

### ISSUE THREAD

**Issue by CynthiaN01** [smtinova/wissArbeiten_gruppenarbeit#3]
Hallo an alle
Weiß jemand ob es möglich ist in github Änderungsvorshläge nur an eine Person zu schreiben, damit die nicht Nr.1 Leute nicht gespoilert werden?
Sonst müsste man bei den issues und pull requests immer auf @... o.ä. achten. 
Oder sollen wir dann immer vorne rein schreiben nur A1 oder so?
Was denkt ihr?

**Comment by novaktim** [comment]
Auf Github konnte man damals Privatnachrichten senden, aber das haben die leider vor ein paar Jahren entfernt.
Soviel ich weiß können wir nur über Issues kommunizieren, welche immer public ansehbar sind.
Ich habe so einen "Milestone" für Aufgabe 1 gemacht, damit kannst du die Issue und mich taggen. Dann darauf achten.

Aber es hat sowieso jeder Contributor Zugriff auf alles, das heißt, die aus Aufgabe 2, könnten sich jederzeit den Code angucken und spoilern, also denke ich nicht, dass wir mit Issues groß auf geheim machen müssen.
Falls es wirklich vertraulich sein soll, dann schreib mir deine Frage über WhatsApp. Bei GitHub läuft das normalerweise auch sonst über angegebene Geschäftsemails.

**Comment by CynthiaN01** [comment]
Ok verstehe.
Also ich kann dir natürlich über Whatsapp schreiben, nur ich dachte, dass wir möglichst viel hier machen, da die Kommunikation mit GitHub auch in die Bewertung einfließt. Aber ich denke das kriegen wir schon, wir müssen ja nicht jede Kleinigkeit hier klären.
Gute Idee mit dem Milestone!
