### ISSUE TITLE
Formatierungen

### ISSUE THREAD

**Issue by CynthiaN01** [smtinova/wissArbeiten_gruppenarbeit#6]
Hier könne wir ab jetzt alles zu dem Thema Formate, Schemata und Zeichen für unsere gemeinsamen Skripte klären.
Dadurch, dass wir uns absprechen sind später unsere R-Skripte lesbarer und verständlicher.

**Comment by CynthiaN01** [comment]
Ergebnis: Die Mehrheit hat für **=** gestimmt.

Nächste Frage: was soll die maximale Länge jeder Zeile sein?

**Comment by novaktim** [comment]
Ich glaube solange es größtenteils lesbar ist, ist das in Ordnung. Jeder wird in seinem eigenem Ermessen wissen, wie viel pro Zeile okay geht. Würde da jetzt keine Zeichengrenze festlegen, zumal die wenigsten beim Programmieren darauf achten.

**Comment by Vince3453463** [comment]
In Compstat wurde uns beigebracht, möglichst weniger als 100 Zeichen pro Zeile zu schreiben, ich denke, daran können wir uns orientieren

**Comment by CynthiaN01** [comment]
Finde ich gut.
Falls jemand sich nicht mit 100 Zeichen zurecht findet,
ihr könnt in RStudio unter Tools > Global Option > Code > Display > General folgendes tun:
Wenn show margin activiert ist, erscheint in Skripten immer ein dünner grauer vertikaler Balken/Strich. Mit margin column kann man einstellen nach wievielen Zeichen er erscheinen soll.
Falls die Zahl größer als 100 ist, könnt ihr sie etwas runter stellen, damit ihr immer beim schreiben wisst, bis wohin ihr schreiben könnt bzw. ab wo ihr nicht mehr schreiben solltet. Eigentlich ganz simpel sich einfach an der Linie zu orientieren.
Wenn ihr fertig mit den Einstellungen seid, mit enter bestätigen.
Ich glaube das ist standardgemäß schon auf eine kleinere Zahl eingestellt.
Ich werde aus Schönheitsgründen, aber nie bis 100 Zeichen oder so hoch gehen.

**Comment by Hanjin99** [comment]
Bei mir habe ich bis jetzt immer mit "Margin column" 80 gearbeitet, falls wir uns auf 100 einigen, ändere ich gerne zu 100. 
Ich finde es gut, dass wir eine Zeichengrenze festlegen.

**Comment by novaktim** [comment]
Das mit der Linie für die maximalen Zeichen ist wirklich ganz cool. Ich kannte das vorher nicht. Dann sieht man direkt wie viel noch frei ist. Habe das nun auf 100 Zeichen eingestellt.

**Comment by Jan-Enno-Jonas** [comment]
100 wäre für mich auch in Ordnung 
Habe bis jetzt nie bewusst auf sowas geachtet

**Comment by CynthiaN01** [comment]
Ok super!
Macht es euch etwas aus, wenn wir etwas unter 100 bleiben? Also, dass alle es auf 90 oder 80 oder so stellen?

**Comment by Hanjin99** [comment]
> Ok super! Macht es euch etwas aus, wenn wir etwas unter 100 bleiben? Also, dass alle es auf 90 oder 80 oder so stellen?

Ich finde 80 gut! (Standardeinstellung bei mir)

**Comment by Hanjin99** [comment]
Ich habe eben für **Funktionen-R-Skript 1.R**, **Funktionen-R-Skript 2.R** und **Aufgabe 4 - Analyse.R** auf margin = 100 angepasst. Viele Zeilen in **Aufgabe 4 - Analyse.R** lassen sich schwer auf 80 oder 90 anpassen. Ich hoffe, dass es für euch in Ordnung ist.

**Comment by CynthiaN01** [comment]
Alles gut, solange es konsequent ist. Danke fürs Anpassen!

**Comment by CynthiaN01** [comment]
Da die Aufgabenteile mit dem Programmieren fertig sind, schließe ich die issue.
