### ISSUE TITLE
Aufgabe 3 als Gruppe bearbeiten

### ISSUE THREAD

**Issue by novaktim** [smtinova/wissArbeiten_gruppenarbeit#8]
Hallo Leute,
da wir Aufgabe 1 und 2 abgeschlossen haben, beginnt jetzt die Bearbeitung von Aufgabe 3 als Gruppe.
Dazu müssen wir gemeinsam 6 verschiedene Funktionen implementieren.
Wenn jemand schon eine Idee hat oder eine Vorstellung, welche Funktion/en er erstellen möchte,
könnt ihr hier bescheidgeben, damit wir nicht die gleiche bearbeiten.

Und außerdem dabei beachten, dass wir interne Funktionen, die nur in Funktionen-R-Skript 1 Anwendung finden auch innerhalb von Funktionen-R-Skript 2 programmieren.

**Comment by Vince3453463** [comment]
Für a) kann man doch einfach summary() verwenden oder? Die berechnet ja Median, mean, Quantile etc automatisch. Oder fallen euch noch  andere sinnvolle despriptive Statistiken für metrische Variablen ein?
für b) fallen mir erstmal nur Modus und absolute Häufigkeiten ein
c) und d) weiß ich nicht genau, was da gefordert ist, soll man da ein lineares Modell erstellen?
e) kann man ja einfach über die Quartilsfunktion einteilen, mit q= 0.33, 0.66 erhält man dann 3 Intervalle, die niedrig, mittel, und hoch enstprechen
f) barplots bieten sich an für kategorielle Variablen

das wären so meine ersten Ideen. Vielleicht können wir ja erst hier als Gruppe diskutieren und die tatsächliche Implementierung dann aufteilen.

**Comment by Jan-Enno-Jonas** [comment]
Bei a) bin ich der Gleichen Meinung wie du Vincent nur bei b) würde ich noch den median dazutun, da zu kategorialen Merkmalen auch die ordinalen dazugehören.
c) und d) finde ich ebenfalls sehr schwer... 
bei e und f bin wieder der Meinung von Vincent aber hier sollte man drauf aufpassen das wir bei e es richtig implementieren

**Comment by CynthiaN01** [comment]
a) finde ich gut, ggf. kann man noch die empirische Varianz angeben, aber Quartile und Interquartilsabstand müssten auch reichen. Hier wird wahrscheinlich ein Boxplot mehr bringen, aber das kommt erst später.
b) Danke für den Hinweis @Jan-Enno-Jonas. Wir könnten ja zwei Funktionen dazu machen oder eine Funktion in der man angeben muss, ob es ein qualitatives oder ordinales Merkmal ist.
c) Vielleicht kann man hier zweidimensionale Häufigkeitstabellen (Kontinggenztafel/Korrelationstabelle) machen und dann die bedingten Verteilungen berechnen, oder im Blick auf das Gesamtbild ein Kontinggenzmaß berechnen. Also sowas wie Korrelation nur für kategorielle Merkmale.
d) Hier können wir entweder das selbe wie oben machen, oder wenn die metrische Variable stetig ist oder zu viele verschiedene Ausprägungen hat, einfach einen Korrelationskoeffizienten aussrechnen. 
Dazu fällt mir auch eine Zusatztfunktion ein für zwei ordinal scalierte Merkmale, man könnte z. B. den Rangkorrelationskoeffizienten berechnen.
e) Hier bin ich eurer Meinung.
f) Ihr habt recht denke ich, aber wenn es um 3 oder 4 Variablen geht ist es mit barplot schwer. Theoretisch geht mfrow = c(2, 2). Auf jeden Fall sollte es etwas sein, dass gut Haufigkeiten darstellt und dann müssen wir es nur noch für mehrere Variablen visualisieren können.

Was mir bis jetzt am meisten auffällt ist, dass es das Meiste schon fertig in R implementiert gibt. Daher frage ich mich ob das reicht und vor allem was in die Helferfunktionen soll. Vielleicht fällt mir auch erst beim Implementieren auf, welchen Aufwand es gibt.

**Comment by novaktim** [comment]
Zu c) bin ich auch der Meinung, dass das nach 4-Felder-Tafel klingt. Damit bedingte Wahrscheinlichkeiten bestimmen und auf stochastische Unabhängigkeit, Korellation prüfen etc.

Bei d) glaube ich nicht, dass man einen Korellationskoeffzienten (lineare Beziehung) bestimmen kann, da die ZV nur 0 oder 1 annehmen kann. Aber man kann mittels logistischer Regression ein Modell berechnen für die Wahrscheinlichkeit, dass bspw. 1 angenommen wird.

f) eignet sich der Barplot wunderbar. Damit lassen sich absolute Häufigkeiten oder andere normierte Werte (z. B. bedingte Wahrscheinlichkeiten) der kategoriellen Merkmale nebeneinander in einem Plot darstellen.

Beim Rest bin ich ganz eurer Meinung.

**Comment by Hanjin99** [comment]
> Zu c) bin ich auch der Meinung, dass das nach 4-Felder-Tafel klingt. Damit bedingte Wahrscheinlichkeiten bestimmen und auf stochastische Unabhängigkeit, Korellation prüfen etc.
> 
> Bei d) glaube ich nicht, dass man einen Korellationskoeffzienten (lineare Beziehung) bestimmen kann, da die ZV nur 0 oder 1 annehmen kann. Aber man kann mittels logistischer Regression ein Modell berechnen für die Wahrscheinlichkeit, dass bspw. 1 angenommen wird.
> 
> f) eignet sich der Barplot wunderbar. Damit lassen sich absolute Häufigkeiten oder andere normierte Werte (z. B. bedingte Wahrscheinlichkeiten) der kategoriellen Merkmale nebeneinander in einem Plot darstellen.
> 
> Beim Rest bin ich ganz eurer Meinung.

Finde ich gut. Bei d). hätte ich jetzt auch logistische Regression gesagt.

**Comment by Hanjin99** [comment]
Wenn niemand etwas dagegen hat, würde ich gerne morgen schon mal mit a). und b). anfangen.
Was wir bis jetzt zur a). und b). haben:

a): summary()-Funktion verwenden, um Minimum, Maximum, 1. Quatil, Median und 3. Quatil zubekommen
     die empirische Varianz ausrechnen und ausgeben

b): qualitatives oder ordinales Merkmal als Eingabe und wird am Ende ebenfalls ausgegeben
     Modalwert, absolute und relative Häufigkeiten der Ausprägungen
     ~Median~

Zwei Fragen:

1. Frage:

Bei der b). können wir nur den Median von den ordinal skalierten Merkmalen berechnen, aber nicht von den qualitativen Merkmalen. Bei der Berechnung benötigen wir dazu die Anordnung der ordinalen Merkmalen als Eingabe. Dazu müssen wir die Anordnung vorher kennen.
Nun habe ich die Merkmale aus 1. angeschaut und es gibt keinen ordinalen Merkmal, deshalb würde ich vorschlagen, Median wegzulassen. Ist es für euch in Ordnung?

2. Frage:

Sollen wir die Rückgaben der Funktionen als Liste speichern?

**Comment by CynthiaN01** [comment]
Ja stimmt, bei d) muss die andere Variable ja dichotom sein. Dann passt das bestimmt besser. Da gibt es eh nur die Variable Mathe-LK.

**Comment by CynthiaN01** [comment]
> 1. Frage:
> 
> Bei der b). können wir nur den Median von den ordinal skalierten Merkmalen berechnen, aber nicht von den qualitativen Merkmalen. Bei der Berechnung benötigen wir dazu die Anordnung der ordinalen Merkmalen als Eingabe. Dazu müssen wir die Anordnung vorher kennen. Nun habe ich die Merkmale aus 1. angeschaut und es gibt keinen ordinalen Merkmal, deshalb würde ich vorschlagen, Median wegzulassen. Ist es für euch in Ordnung?
> 
> 2. Frage:
> 
> Sollen wir die Rückgaben der Funktionen als Liste speichern?

1. Einerseits würde ich jetzt zustimmen. Andererseits wird man (z.B. in (e)) die quantitativen Mermale kategorisieren und dann wären sie ordinal skaliert. Deswegen würde ich trotzdem die Funktion(en) für b) darauf anpassen, dass das Mermal ordinal oder nur qualitativ sein kann, denn die Funktionen müssen nicht nur auf die Hauptdaten angewendet werden. Daher mein Vorschag, dass man der Funktion das Argument has.order oder so übergibt, oder dass man zwei Funktionen schreibt. Und je nach dem wendet man die passenden deskriptiven Statistiken an.

2. Ich wäre dafür. Wir könnten zum Beispiel sobad es mehr als einen Rückgabewert hat benannte Listen zurück geben und sonnst einen benannten Vektor. Aber was dann in der Konsole erscheint muss nicht unbedingt die rückgabe sein. Man kann z.B. etwas schönes printen und im Hintergrund die Liste zurückgeben. Trotzdem würde ich das nicht komplett festlegen, denn es hängt von den Rückgabewerten ab, was sinnvoll ist. Vielleicht kann sich jeder einfach hieran orientieren und selbst überlegen, ob es in seinem Fall sinnvoll ist.

**Comment by CynthiaN01** [comment]
Ich mache mich dann an Aufgabe (c) und versuche auch meine Ideen für Zusatzfunktionen umzusetzen.

**Comment by CynthiaN01** [comment]
Zu e) noch eine Verständnisfrage.
>e) kann man ja einfach über die Quartilsfunktion einteilen, mit q= 0.33, 0.66 erhält man dann 3 Intervalle, die niedrig, mittel, >und hoch enstprechen

War damit gemeint, dass man im Vektor der Realisierungen die Quantile bildet? Denn das wäre nicht sehr sinnvoll denke ich, denn sonst haben alle Kategorien immer die selbe Häufigkeit. Oder war gemeint, dass man die Ausprägungsmöglichkeiten in Quantile einteilt, z.B. bei einer Variable, die die Werte {1, 2, 3, 4, 5, 6} annehmen kann, die Quantile auf {1, 2}, {3, 4}, und {5, 6} einzuteilen und dann zu bestimmen, wieviele Ausprägungen in welcher Kategorie sind?

Vielleicht erscheint die Antwort jetzt ersichtlich, aber ich wollte nur sicher gehen, dass wir an das selbe gedacht haben. Also 1. oder 2.?

**Comment by novaktim** [comment]
Die Aufgabe e) ist nicht strikt formuliert, deshalb steht auch nur "z. B. niedrig, mittel, hoch" also können wir die an und für sich implementieren wie wir möchten. 
Man könnte zwar der Funktion ein Argument übergeben, indem die Grenzen fix festgelegt werden wie z. B. beim Alter dass man die Jahresgrenzen übergibt. Aber da die Aufgabe explizit sagt, dass man die quantilbasiert kategorisieren soll, würde ich schon über die Quantile gehen. Auch wenn die dann immer nahezu "gleich groß" sind. Aber man könnte auch z. B. q = 0.25, 0.75 für die 3 Quantile übergeben, dann ist mittel doppelt so groß wie die anderen beiden.

**Comment by Vince3453463** [comment]
> 

Das Problem an Methode 1 ist, dass Variablen ja auch Werte auf ganz R annehmen können, da kann man dann schlecht Kategorien bilden. Zudem muss man dann ja für jede mögliche Variable die Ausprägungsmöglichkeiten irgendwie als Argument übergeben, was bei jeder Variable ein bisschen anders sein kann. Wenn wir über die Quantile der Daten gehen, ersparen wir uns viele Probleme und die Funktion ist universell anwendbar.

Wenn ich das richtig überblicke, macht Hanjin a) und b), Cynthia c) und freiwillige weitere Funktionen und Tim hat d) schon gemacht? Da e) übrig ist, würde ich das dann versuchen und für Enno bleibt f)

**Comment by Jan-Enno-Jonas** [comment]
Ist für mich in Ordnung 
Habe nur die nächsten Tage kaum Zeit...
Werde es frühestens nächstes Wochenende schaffen 
Sorry

**Comment by CynthiaN01** [comment]
Ok, ich verstehe was ihr meint, aber ich bin noch nicht ganz zufrieden.
Wenn man den Vektor einfach in sagen wir mal 3 Teile teilt, egal wie groß sie sind, was gibt die Funktion dann nachher zurück? Macht die funktion dann wie bei split 3 Teilmengen? Außerdem können unlogische Ergebnisse dabei rauskommen, denn die gleiche Mermalsausprägung könnte in mehreren Kategorieen sein, z.B. bei der Imteresse an Mathe oder Programmieren, könnten einige 4-en in "niedrig" und einige in "mittel" sein und welche davon dann zu welchem Studenten gehört ist entweder zufällig oder deterministisch und am Ende sagt man, dass  bei diesen Studenten mehr niedrig war und bei diesen mehr mittel, obwohl beide dieselbe Angabe beim Interesse hatten, dabei hing es nur von der Reihenfolge im Vektor ab, welche 4 zu wem/zu welcher Kategorie gehört. 
Die Information, die man durch das Unterteilen in Quantile bekommt, ist, denke ich, nicht die, die wir hier brauchen. Die Quantile gibt man ja auch schon in den Funktionen aus a) und b) zurück.
Stellt euch mal vor es wird angenommen, dass die Befragten alle 25 Jahre alt sind, aber am ende stellt man fest, dass 76% jünger als 25 war. Dann würde diese Funktion das Alter 25 nicht mehr als mittel einordnen, sonder als hoch, obwohl es nur ein junger Jahrgang war. Ich hoffe mit diesen Beispielen versteht ihr was ich meine.

Wir können es so machen: Man gibt der Funktion an wieviele Kategorien man möchte (man kann festegen, dass es nur zwischen 2 und 5 sein darf zum Beispiel, damit man sie danach benenn kann) und man gibt der Funktion einen Vektor der Länge = AnzahlKategorien -1. In diesem Vektor stehen dann die zwischen Intervallgrenzen (die breaks; Funktion cut() ist hilfreich) und die Außengrenzen sind dann einfach minus und plus unendlich. Dann kann die Funktion am Ende die Häufigkeiten in jeder Kategorie ausgeben und man kann durch die Funktion erfahren ob es eher Ausprägungen, die hoch oder niedrig sind gibt, nach seinem eigenen Maß.
Bestimmt fallen einem beim Implementieren noch weitere Ideen oder Parameter für die Funktion ein.
Wenn ihr wollt kann man auch als default sagen, wenn du mir keine zwischen-Intervallgrenzen gibst, dann bilde ich einfach quantile der Größe ... .

Trotzdem bin ich mir noch unsicher, denn in der Aufgabenstellung steht quantilbasiert, also würde das eher für das sprechen, was ihr meint, nur finde ich das irgendwie nicht sinnvoll. Man gibt einfach Kategorien einen Namen, der auch gar nicht zu den Ausprägungen in der Kategorie passen könnte. Und das Aufteilen in Quantile passt eher zur Deskribierung, wie in a) und nicht zur Kategoriesierung aus e), meiner Meinung nach.

**Comment by Vince3453463** [comment]
Den ersten Entwurf habe ich so implementiert (zur Zeit nur für numerische Daten), dass ein dataframe returned wird, in dem in der ersten Spalte die ursprünglichen Daten stehen und in der 2. Spalte die Kategorie, als niedrig, mittel, hoch. Der Informationsgewinn dieser Funktion ist also die Einschätzung jedes Datenpunktes wo er sich ordnungsmäßig innerhalb des Vektors befindet. Der Unterschied zu den Funktionen aus a) ist also, dass man sich diesmal nicht auf die Quantile beschränkt, sondern für jeden einzelnen Datenpunkt etwas berechnet.

Als Parameter der Funktion kann man die gewünschten Quantile übergeben, mit 0.25 und 0.75 als default wie Tim es vorgeschlagen hat.

Ich kann nicht so ganz verstehen, was du meinst, warum ist die Reihenfolge der Daten im Vektor relevant? Ruft man nicht die Funktion genau einmal mit den Daten auf und hat dann genau für diese Daten passende Quantile? 
Das Problem an deiner Vorgehensweise ist es, dass man als Anwender schon eine sehr genaue Vorstellung über die Verteilung der Daten haben muss, um überhaupt zu wissen, was niedrig und hoch sein soll. Dann braucht man aber auch keine Helferfunktion mehr denke ich, sondern kann es auch hartcoden. Der Sinn dieser Helferfunktionen soll es ja meinem Verständnis nach sein, mehr über die Daten herauszufinden. Die genaue Kenntniss über die Verteilung als Vorraussetzung anzunehmen halte ich daher nicht so sinnvoll.

Ein anderes Problem ist, wie man es implementiert, falls die Daten nicht numerisch sind, die Ordnungsrelation also irgendwie als Parameter übergeben werden soll. Da bin ich für Vorschläge dankbar ^^

**Comment by novaktim** [comment]
Ich würde mir da auch nicht so viele Gedanken zu machen. Um ehrlich zu sein, kann ich mir nur schlecht vorstellen, dass die Funktion überhaupt später bei den Erkenntnissen helfen wird, da man durch die Kategorisierung in Klassen eigentlich nur an Information verliert. 
Ich glaube die Aufgabe ist wirklich keine Raketenwissenschaft. Sondern soll tatsächlich so impementiert werden, wie sie formuliert wurde, über Quantile. Da schon "z.B. niedrig, mittel, hoch" steht, ist es uns überlassen, ob wir die drei Klassen hardcoden oder als variables Argument übergeben. 
Jedenfalls will ich noch mal daran erinnern, dass wir zwei Wochen bis zur Abgabe haben und noch Aufgabe 4 und 5 vor uns haben. Zumal bestimmt viele von uns noch für andere Klausuren lernen müssen. Ich will damit nur sagen, dass wir nicht aus jeder Mücke einen Elefanten machen sollten. Perfektion hat ihre Grenzen. Je mehr Zeit wir für diese kleine Teilaufgabe aufbringen, desto weniger bleibt uns für den Rest. Und dann könnte das Projekt zu einem schlechteren Ergebnis kommen, obwohl wir eigentlich mehr Arbeit reingesteckt haben.

@Vince3453463 bzgl. ordinal skalierten Variablen. Wenn ich mich nicht irre, werden Ordinalskalen mit factor erstellt, und zwar so, dass die zugrunde liegende numerische Zahl im Hintergrund, die Rangordnung angibt. Lese dazu vielleicht nochmal in der Hilfeseite nach, aber bestimmt reicht es, die Variable mit as.numeric zu konvertieren und dann kannst du wie gewohnt die Quantile bilden. Dann kommt zwar eine Kommazahl heraus, und jeder Rang landet in der gleichen Klasse, aber ich denke das soll so sein.

**Comment by Vince3453463** [comment]
Du hast Recht, as.numeric funktioniert für ordinalskalierte Variablen. Dann vereinfacht sich diese Aufgabe sehr. Letzte Frage: Ist es okay, hier ein dataframe zu returnen? Für diese Aufgabe passt das meiner Meinung nach besser und sieht schöner aus als eine Liste, da dann die Zuordnung: Datenpunkt -> Kategorie sofort ersichtlich ist.

**Comment by CynthiaN01** [comment]
So wie du es beschrieben hast denke ich auch, dass ein Data Frame besser passt. Für mich ist es kein Problem.

**Comment by CynthiaN01** [comment]
> Ich kann nicht so ganz verstehen, was du meinst, warum ist die Reihenfolge der Daten im Vektor relevant? Ruft man nicht die Funktion genau einmal mit den Daten auf und hat dann genau für diese Daten passende Quantile? 

>Das Problem an deiner Vorgehensweise ist es, dass man als Anwender schon eine sehr genaue Vorstellung über die Verteilung der Daten haben muss, um überhaupt zu wissen, was niedrig und hoch sein soll. 

> Um ehrlich zu sein, kann ich mir nur schlecht vorstellen, dass die Funktion überhaupt später bei den Erkenntnissen helfen wird, da man durch die Kategorisierung in Klassen eigentlich nur an Information verliert. 

Wir können das so implementieren, wie ihr es vorgeschlagen habt, trotzdem möchtet ich nochmal auf etwas aufmersam machen.

Ich denke die Funktion wird später insofern helfen, dass sie die Variablen durch eine Kategorisierung viel übersichtlicher macht und man auf die kategorisierten Variablen, die dann ordinal sind, die Funktionen b), c) und f) anwenden kann. Die Kategorien an sich sind natürlich kein großer Gewinn.
Man kann sich einfach mit den Funktionen  aus a) und b) ein Überblick verschaffen und dann Intervallzwischengrenzen festlegen, aber in den meisten Fällen weiß man schon was niedrig und was hoch ist. Und wenn nicht, würde man auch ohne ein data frame in dem steht, dass Merkmalsausprägung x1 niedrig ist, wissen, dass x1 niedrig ist, denn man kennt ja durch die Quantile bereits unter welchem Wert/welcher Ausprägung die unteren 25% liegen (Beispiel zur Verdeutlichung: x1 = 22,4 Jahre alt, in dem data frame steht 22.4 -> niedrig, aber man wusste schon durch die Quantile, dass es eher niedrig ist, denn das 25% Quantil ist 23.4, also kein Informationsgewinn). Es schadet bestimmt nicht nochmal eine Liste zu haben in welcher in der richtigen Reihenfolge steht, welche ID in welche Kategorie kommt, nur sagen diese Kategorien nicht viel aus, denn sie sind genau auf die Ausprägungen dieser Variable ausgerichtet. Zum Beispiel: Interesse an Mathe und Interesse an Programmieren, bei dem einen ist 5 hoch, bei dem anderen mittel. Aber das ist gar nicht das Hauptaugenmerk. Bestimmt kann man hier noch Gegenargumente finden.

Was ich eigentlich problematisch fand ist das Problem mit der Zuordnung gleicher Merkmalsausprägungen. Ich glaube das war oben noch nicht ganz verständlich von mir ausgedrückt
Wenn die Variable stetig ist, dann gibt es i.d.R. keine identischen Ausprägungen. Andernfalls 
ich nehme mal wieder ein Beispiel von hier. Man unterteilt das Interesse an Mathematik in die Kategorien niedrig mittel hoch mittels der Quartile. Betrachten wir das untere Quartil. Einige 3-en sind in der Kategorie niedrig, der Rest in der Kategorie mittel. Je nach Sortierung gehören die 3en aus der Kategorie niedrig den Studenten a, b, c, d, e und die restlichen 3en den Studenten f bis t. Also haben einige Studenten angeblich ein niedriges Interesse und andere ein mittleres, obwohl sie das selbe angegeben haben. Dabei bleibt es nicht. Wenn man im nächsten Schritt untersucht, welche Studenten nach Studiengang welches Interesse haben, werden die Ergebnisse auch beeinflusst. Sind zum Beispiel zufällig die Studenten a bis e aus den Studiengängen Mathe und Statistik (und f bis t eine Mischung aus allen 4), dann würde für die Mahte und Statistik Studiengänge mehr Studenten mit niedrigem Interesse an Mathematik herauskommen, obwohl sie dieselben Angaben gemacht haben, wie die Studenten f bis t, doch bei f-t wird für den jeweiligen Studiengang der Zähler von mittel immer eins hoch gesetzt. Die Ergebnisse werden dadurch verändert, vor allem wenn es nicht so viele Studenten gibt

Max und Min nehmen und Quantile bilden geht nicht immer und ist nicht immer sinnvoll, 
Zwischengrenzen festlegen funktioniert, fordert aber gewisse Kenntnisse,
aber Quantile der Variable bilden und danach aufteilen sagt am Ende nichts neues aus. 
Man kann auf einem Mal sehen welche Ausprägung in welchem Quantil ist, aber wenn man es später nach einer weiteren Variable aufteilt, kann man nicht mit Sicherheit wissen, ob die Ergebnisse komplett sinnvoll sind oder nicht einfach nur von der Verteilung der ersten Variable beeinflusst.

Trotzdem ist es am einfachsten ... ok. Ich hoffe einfach, dass diese Dinge die Ergebnisse nicht verschlechtern, aber vielleicht muss man sie dann einfach anders interpretieren.
Wenn ihr immer noch für die Quantile im Vektor seid, ok dann machen wir es so.
Wenn noch Zeit ist, dann kann man ja beides implementieren, aber wie Tim schon meinte, lasst uns erstmal vorankommen. Ich habe dabei nur an das Gelingen des Projekts gedacht, war nicht als Schönheitsmarkel gemeint. Wäre ja blöd, wenn es falsch ist, aber dafür könnten wir nichts, denn die Aufgabenstellung gibt nicht klar hervor wie und wo die Quantile gebildet werden sollen (zu mindest nicht für mich).

**Comment by Jan-Enno-Jonas** [comment]
Bei der Visualisierung habe ich überlegt es mit Boxplots zu machen, aber ich bin mir gerade nicht sicher ob man Boxplots für kategorialen Merkmalen immer nehmen kann, glaube aber schon was meint ihr passt für Boxplots?

**Comment by Vince3453463** [comment]
Boxplots braucht ja Quantile, ist also im Allgemeinen nicht möglich für kategorielle Daten.

Die trivialste Lösung, die mir einfällt, ist da einfach ein barplot für jede Variable zu machen. Mit par(mfrow = c(2,2)) kann man die dann nebeneinder betrachten, Laut Aufgabenstellung werden ja 3 oder 4 Variablen übergeben.

**Comment by Vince3453463** [comment]
Ich habe ein pull request für 3e) erstellt, bitte mal testen.

**Comment by Jan-Enno-Jonas** [comment]
Stimmt hast Recht 

ich habe kategoriale Merkmal mit metrische Merkmalen verwechselt🙈

**Comment by Hanjin99** [comment]
Aufgabe 3 ist nun komplett.
